service: movie-bot

provider:
  name: aws
  runtime: nodejs6.10
  role: arn:aws:iam::786856905369:role/parallel-api-lambda
  region: us-east-2

functions:
  
  getRating:
    handler: handler.getRating
    environment:
      OMDB_ACCESS_KEY: ${env:OMDB_ACCESS_KEY}
    events:
      - http:
          path: rating
          method: post
  
  compareMovies:
    handler: handler.compareMovies
    environment:
      OMDB_ACCESS_KEY: ${env:OMDB_ACCESS_KEY}
    events:
      - http:
          path: compare
          method: post
  getDetails:
    handler: handler.getDetails
    environment:
      OMDB_ACCESS_KEY: ${env:OMDB_ACCESS_KEY}
    events:
      - http:
          path: details
          method: POST
